# Generated by Django 4.1.1 on 2022-10-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Anonimous",
                        max_length=40,
                        null=True,
                        verbose_name="Автор",
                    ),
                ),
                ("text", models.TextField(max_length=400, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Запись создана"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Запись изменена"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="webapp.article",
                        verbose_name="Статья",
                    ),
                ),
            ],
        ),
    ]
